Fix session lost with `signed: true`
redis-store/redis-actionpack pull request #35
Opened 2020-10-19 21:43 UTC by kazk

Override `extract_session_id` to get decrypted/unsigned value.

https://github.com/rack/rack/blob/5ce5b2ccb151c62652e25b4711218ede11497cc3/lib/rack/session/abstract/id.rb#L318-L324
https://github.com/rack/rack/blob/5ce5b2ccb151c62652e25b4711218ede11497cc3/lib/rack/session/abstract/id.rb#L476-L479

Fixes https://github.com/redis-store/redis-rack/issues/56

2020-10-19 21:56 UTC, tubbo requested changes
Great start, thanks for taking the initiative on this! 

Can you write a test for this functionality as well? Make sure you run the test with your changes commented out, to make sure that you're not getting a false positive.

2020-10-20 02:47 UTC, kazk commented on test/integration/redis_store_integration_test.rb
> +      assert_equal 'foo: "bar"', response.body
For some reason, the fix isn't working in tests :(

2021-04-07 18:17 UTC, tubbo commented
this PR needs to pass tests before i can merge it, let me know if you need any help

2021-04-07 21:10 UTC, kazk commented
I forgot about this PR. I just quickly looked into the cause of the test failure again, and noticed that `cookies` in `ActionDispatch::IntegrationTest` is `Rack::Test::CookieJar` which doesn't support signed/encrypted. On the other hand, the cookie jar in the dummy app is `ActionDispatch::Cookies::CookieJar`. Maybe the failure is related to this? I'm pretty sure that demo app was fixed with this change according to my comments, but I honestly don't remember much.


I'd appreciate if you can take it from here because I don't need the fix anymore. If not, I'll close it.

2021-05-27 20:44 UTC, closed without merging